module.exports = {
  'Creating an activity' : function(driver)
  {
    driver
    .url(driver.globals.userNames.adminURL)
    .windowMaximize("current")
    .waitForElementVisible('body', 2000)
    .useXpath()
    .click("//input[@id='admin_email']")
    .pause(2000)
    .setValue("//input[@id='admin_email']", driver.globals.userNames.adminEmail)
    .pause(2000)
    .click("//input[@id='admin_password']")
    .pause(2000)
    .setValue("//input[@id='admin_password']", driver.globals.userNames.adminPassword)
    .pause(2000)
    .click("//input[@class='btn btn-login test-login-button']")
    .pause(4000)
    .click("//a[@class='test-nav-hubs']")
    .pause(4000)
    .click("//a[@class='btn btn-default btn-icon-add test-hub-new']")
    .pause(2000)
    .click("//div[@id='new_mission_hub']/div/div/div[2]/div/div/input")
    .pause(2000)
    .setValue("//div[@id='new_mission_hub']/div/div/div[2]/div/div/input", "Sharing Tools")
    .pause(2000)
    .click("//div[@class='modal-footer ng-scope']/button")
    .pause(3000)
    .click("//li[@class='q-builder-click test-hub-new-activity']")
    .pause(4000)
    .click("//a[@class='rowclick test-hub-structure-item-link ng-binding']")
    .pause(4000)
    .click("//button[@class='btn-edit']")
    .pause(2000)
    .clearValue("//div[@class='ng-isolate-scope ng-pristine ng-valid']/input")
    .pause(2000)
    .setValue("//div[@class='ng-isolate-scope ng-pristine ng-valid']/input", "Sharing Tools Activity")
    .pause(2000)
    .click("//textarea[@class='mission-page-title test-activity-name ng-pristine ng-valid placeholder']")
    .pause(2000)
    .setValue("//textarea[@class='mission-page-title test-activity-name ng-pristine ng-valid placeholder']", "Sharing Tool Activity name")
    .pause(2000)
    .click("//textarea[@class='q-field q-field-medium test-activity-tagline ng-pristine ng-valid placeholder']")
    .pause(2000)
    .setValue("//textarea[@class='q-field q-field-medium test-activity-tagline ng-pristine ng-valid placeholder']", "Mission offer")
    .pause(2000)
    .click("//input[@id='switch_cb_activity.page.show_image']")
    .pause(2000)
    .click("//input[@id='switch_cb_activity.page.show_details']")
    .pause(2000)
    .click("(//div[@class='wysiwyg'])[1]/textarea")
    .pause(2000)
    .setValue("(//div[@class='wysiwyg'])[1]/textarea", "Mission Details")
    .pause(2000)
    .end();

  }



}
